net:
  service:
    syslog:
      - address: syslog-archive.example.com
        port: 514
        protocol: udp
      - address: logstash.example.com
        port: 5514
        protocol: tcp
    zabbix:
      - address: zabbix.example.com
      - address: zabbix2
        port: 10051
